### ISSUE TITLE
`rake device` fails for my iPhone XS due to new upper case device id

### ISSUE THREAD

**Issue by skovsboll** [amirrajan/rubymotion-templates#14]
Just noticed a difference from my iPhone 7 to the new XS.

`rake device` fails with `Device ID '00008020-0012698E0198002E' not provisioned in profile [...]`

It's the correct device ID: 

```bash
> idevice_id -l
00008020-0012698E0198002E
```

And it's in the profile:

```xml
	<key>ProvisionedDevices</key>
	<array>
		<string>ed8e6ecaa50fd2bd8dc0e8351404968c00469761</string>
		<string>00008020-0012698E0198002E</string>  
	</array>
```

The first is my 7 Plus, the last is my XS.

Line 282 in `ios.rb` downcases before checking the provisioning profile

```ruby
  device_id = (ENV['id'] or App.config.device_id).downcase
```

I'll submit a PR with a fix. Just wanted to give some context and have the discussion before submitting out of the blue :)

**Comment by skovsboll** [comment]
Before I submit a PR, could you folks help testing this on other device types please?

**Comment by amirrajan** [comment]
@skovsboll I don't have an XS (yet). But if it works for you, I'm fine incorporating the change 👍

**Comment by amirrajan** [comment]
I'll verify that existing devices aren't broken of course (will merge this in this weekend).

**Comment by amirrajan** [comment]
I tried using the current rubymotion templates and typed: `rake device_name='iPhone XS'` and the correct simulator popped up (w/o the need for your patch).

I did try your patch however, and it didn't break anything (and also brought up the correct simulator). Have I overlooked something?

**Comment by skovsboll** [comment]
This problem manifests only when running the app on physical devices. The error is raised inside the `:device` rake task only:  https://github.com/amirrajan/rubymotion-templates/blob/master/motion/project/template/ios.rb#L283

The simulator bypasses the check for device id in the provisioning profile, so it will always work there.

**Comment by amirrajan** [comment]
Thanks for the clarification 👍
