### ISSUE TITLE
Don't forget to do this Amir

### ISSUE THREAD

**Issue by amirrajan** [amirrajan/rubymotion-templates#26]
![image](https://user-images.githubusercontent.com/517055/64476872-f1c49e80-d159-11e9-9d60-3c104fd0960e.png)

**Comment by andrewhavens** [comment]
Pretty sure this is done. Looking at my version in 6.4, I see that line was updated.

**Comment by andrewhavens** [comment]
Now that `project.rb` is part of this repo, this has been fixed.
