### ISSUE TITLE
`motion doctor` check Swift

### ISSUE THREAD

**Issue by andrewhavens** [amirrajan/rubymotion-templates#28]
I recently upgraded Xcode and RubyMotion and ran into an error with missing `libswiftCore.dylib`. I forgot about the "copy Swift dylibs" step and didn't see it mentioned anywhere, so I wasn't sure if this was still necessary. I ran `motion doctor` and it reported everything was as expected. I noticed in [`doctor.rb`](https://github.com/amirrajan/rubymotion-templates/blob/master/doctor.rb#L42) that it's only checking RM 6.0-6.2 (I had upgraded to 6.5). If this is just a matter of updating the array, I can do that, but I'm wondering if this is the best solution.

**Comment by andrewhavens** [comment]
Also, I ran `cp -r /usr/lib/swift/*.dylib /Applications/Xcode.app/Contents/Frameworks/` and got permissions issues. I'm not sure if I should simply prefix with `sudo` (even though I haven't had to do that before) or if this is a sign of a different problem.

**Comment by amirrajan** [comment]
yep, you have to use `sudo`. Catalina removed this directory, so I'd probably hold off on this (we won't have to do this additional step).

**Comment by andrewhavens** [comment]
I ran into this problem again recently. PR #48 fixes this issue by not hard-coding the versions that it applies to.
