### ISSUE TITLE
an app needs to be notarized using notarytool instead of altool starting November 1st. 

### ISSUE THREAD

**Issue by wndxlori** [amirrajan/rubymotion-templates#63]
https://github.com/amirrajan/rubymotion-templates/blob/3206208d0c94db928e8e9343c93b9571ed294889/motion/project/template/osx/notarizer.rb#L226

**Comment by digitalmoksha** [comment]
[TN3147: Migrating to the latest notarization tool](https://developer.apple.com/documentation/technotes/tn3147-migrating-to-the-latest-notarization-tool)

**Comment by andrewhavens** [comment]
I think there is already an open PR for fixing this: #64 (authored by @digitalmoksha)

**Comment by digitalmoksha** [comment]
#64 has been merged, @wndxlori this can probably be closed now
